version: '3'

services:
    httpd:
      build: ./httpd/
      image: php7-server:ubuntu-18.04
      ports:
        - 80:80
        - 443:443
        - 9000:9000
      # restart: always
      depends_on:
        - mysql
      networks:
        - default
      tmpfs:
        - /var/www/html/var/cache:exec,mode=777
        - /var/www/html/var/log:exec,mode=777
      volumes:
        - ./logs/apache:/var/log/apache2
        - ./httpd/apache:/etc/apache2/sites-available
        - ./httpd/repos:/var/www
        - ./httpd/enterprises/selectech:/selectech
        - ./httpd/enterprises/svs:/svs
      extra_hosts:
        - "i9.local:192.168.99.100"
        - "taq.local:192.168.99.100"
        - "wfm.local:192.168.99.100"  
    mysql:
      build: ./mysql/
      image: php7-db:mysql-5.6.40
      environment:
        MYSQL_DATABASE: project
        MYSQL_USER: admin
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: password
      ports:
        - 3306:3306
      networks:
        - default
      volumes:
        - ./logs/mysql:/var/log/mysql
        # Put .sql / .sql.gz to this folder to create new db every time
        - ./data:/docker-entrypoint-initdb.d
        # or use persistent Database
        - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  default: